[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
apexpad_locker = "AL7nyF8UR5MsmXrmnCf8SoAyT7ccK2DDQh6GZufbWcje"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/workspaces/codespaces-blank/apexpad-locker/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/apexpad-locker"]

